name: Release to maven central

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Repsy repository
        uses: actions/setup-java@v4
        with: # running setup-java again overwrites the settings.xml
          java-version: '17'
          distribution: 'adopt'

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Log Settings.xml
        run: |
          cat .github/settings.xml 

      - name: Publish to Repsy
        run: ./mvnw -B -s .github/settings.xml -Darguments=-DskipTests release:prepare release:perform
        env:
          MAVEN_USERNAME: ${{ secrets.REPSY_USER }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.REPSY_PASSWORD }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}

      - uses: actions/checkout@master
      - name: Merge release -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: release
          target_branch: main
          github_token: ${{ github.token }}

      - name: Merge release -> development
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: develop
          github_token: ${{ github.token }}
